using MuaythaiApp.Api.Security;
using Npgsql;

namespace MuaythaiApp.Api.Data;

public sealed class DatabaseInitializer
{
    private readonly PgConnectionFactory connectionFactory;

    public DatabaseInitializer(PgConnectionFactory connectionFactory)
    {
        this.connectionFactory = connectionFactory;
    }

    public async Task InitializeAsync()
    {
        await using var connection = connectionFactory.Create();
        await connection.OpenAsync();

        var command = connection.CreateCommand();
        command.CommandText =
        """
        CREATE TABLE IF NOT EXISTS clubs (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            coach text NULL,
            city text NULL,
            country text NULL
        );

        CREATE TABLE IF NOT EXISTS fighters (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name text NOT NULL,
            last_name text NOT NULL,
            weight double precision NOT NULL DEFAULT 0,
            age integer NOT NULL DEFAULT 0,
            club_id integer NOT NULL DEFAULT 0,
            birth_year integer NOT NULL DEFAULT 0,
            gender text NOT NULL DEFAULT '',
            age_category text NOT NULL DEFAULT '',
            weight_category text NOT NULL DEFAULT ''
        );

        CREATE TABLE IF NOT EXISTS categories (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            division text NOT NULL,
            gender text NOT NULL,
            age_min integer NOT NULL,
            age_max integer NOT NULL,
            weight_max double precision NOT NULL,
            is_open_weight boolean NOT NULL DEFAULT false,
            sort_order integer NOT NULL,
            category_name text NOT NULL,
            round_count integer NOT NULL DEFAULT 3,
            round_duration_seconds integer NOT NULL DEFAULT 120,
            break_duration_seconds integer NOT NULL DEFAULT 60
        );

        CREATE TABLE IF NOT EXISTS matches (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fighter1_id integer NOT NULL DEFAULT 0,
            fighter2_id integer NOT NULL DEFAULT 0,
            fighter1_name text NOT NULL DEFAULT '',
            fighter2_name text NOT NULL DEFAULT '',
            age_category text NOT NULL DEFAULT '',
            weight_category text NOT NULL DEFAULT '',
            gender text NOT NULL DEFAULT '',
            category_group text NOT NULL DEFAULT '',
            order_no integer NOT NULL DEFAULT 0,
            judges_count integer NOT NULL DEFAULT 5,
            day_number integer NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS judge_scores (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id integer NOT NULL,
            round_no integer NOT NULL,
            judge_id integer NOT NULL,
            red_points integer NOT NULL,
            blue_points integer NOT NULL,
            red_warning boolean NOT NULL DEFAULT false,
            blue_warning boolean NOT NULL DEFAULT false
        );

        CREATE TABLE IF NOT EXISTS match_results (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id integer NOT NULL,
            winner text NOT NULL DEFAULT '',
            method text NOT NULL DEFAULT '',
            round integer NOT NULL DEFAULT 1,
            judge_red integer NOT NULL DEFAULT 0,
            judge_blue integer NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS app_settings (
            key text PRIMARY KEY,
            value text NOT NULL
        );
        """;

        await command.ExecuteNonQueryAsync();
        await EnsureDefaultPasswordsAsync(connection);
    }

    private static async Task EnsureDefaultPasswordsAsync(NpgsqlConnection connection)
    {
        await EnsureSettingAsync(connection, "AdminPasswordHash", PasswordHasher.Hash("Admin123!"));
        await EnsureSettingAsync(connection, "UserPasswordHash", PasswordHasher.Hash("User123!"));
    }

    private static async Task EnsureSettingAsync(NpgsqlConnection connection, string key, string value)
    {
        var command = connection.CreateCommand();
        command.CommandText =
        """
        INSERT INTO app_settings (key, value)
        VALUES (@key, @value)
        ON CONFLICT (key) DO NOTHING
        """;
        command.Parameters.AddWithValue("@key", key);
        command.Parameters.AddWithValue("@value", value);
        await command.ExecuteNonQueryAsync();
    }
}
