using System;
using System.Collections.Generic;

namespace MuaythaiApp;

public enum AppLanguage
{
    English,
    Polish
}

public static class LocalizationService
{
    private static readonly Dictionary<string, string> English = new()
    {
        ["Language"] = "Language",
        ["English"] = "English",
        ["Polish"] = "Polish",
        ["MainTitle"] = "MuaythaiApp",
        ["Fighters"] = "Fighters",
        ["Clubs"] = "Clubs",
        ["Categories"] = "Categories",
        ["Matches"] = "Matches",
        ["FightResults"] = "Fight Results",
        ["MedalTable"] = "Medal Table",
        ["Reports"] = "Reports",
        ["ChangePasswords"] = "Change Passwords",
        ["DatabaseSync"] = "Database Sync",
        ["CurrentDatabase"] = "Current database",
        ["SharedDatabasePath"] = "Shared database path",
        ["DatabaseSyncHint"] = "Use the same shared network database file path on both computers to see the same tournament data.",
        ["DatabaseSyncInfo"] = "If the target database file does not exist yet, the app copies your current data into it automatically.",
        ["DatabaseSyncSaved"] = "Database sync settings saved.",
        ["DatabaseSyncSaveFailed"] = "Database sync could not be saved",
        ["SharedDatabasePathRequired"] = "Enter a shared database path.",
        ["DatabasePathMustEndWithDb"] = "Database path must end with .db",
        ["InvalidDatabasePath"] = "Database path is not valid.",
        ["UsingLocalDatabase"] = "Now using this computer's local database.",
        ["UsingLocalDatabaseLabel"] = "Using local database",
        ["UsingSharedDatabaseLabel"] = "Using shared database",
        ["UseLocalDatabase"] = "Use Local Database",
        ["Save"] = "Save",
        ["Cancel"] = "Cancel",
        ["Logout"] = "Logout",
        ["LoggedInAsAdministrator"] = "Logged in as administrator",
        ["LoggedInAsUser"] = "Logged in as user",
        ["FullAccessEnabled"] = "Full access enabled. Administrator can edit fighters, clubs, matches and passwords.",
        ["LimitedAccessEnabled"] = "Limited access enabled. This account can only view categories, fight results, medal table and reports.",
        ["FighterRegistration"] = "Fighter Registration",
        ["FirstName"] = "First Name",
        ["LastName"] = "Last Name",
        ["Club"] = "Club",
        ["BirthYear"] = "Birth Year",
        ["Age"] = "Age",
        ["Weight"] = "Weight",
        ["Gender"] = "Gender",
        ["Category"] = "Category",
        ["WeightClass"] = "Weight Class",
        ["AddFighter"] = "Add Fighter",
        ["UpdateFighter"] = "Update Fighter",
        ["DeleteFighter"] = "Delete Fighter",
        ["ClearForm"] = "Clear Form",
        ["SearchFighter"] = "Search Fighter",
        ["SortBy"] = "Sort By",
        ["Name"] = "Name",
        ["Surname"] = "Surname",
        ["ClubsTitle"] = "Clubs",
        ["ClubName"] = "Club Name",
        ["Coach"] = "Coach",
        ["City"] = "City",
        ["Country"] = "Country",
        ["AddClub"] = "Add Club",
        ["UpdateClub"] = "Update Club",
        ["DeleteClub"] = "Delete Club",
        ["Clear"] = "Clear",
        ["Search"] = "Search",
        ["ExistingClubs"] = "Existing Clubs",
        ["CategoryManagement"] = "Category Management",
        ["Division"] = "Division",
        ["Info"] = "Info",
        ["All"] = "All",
        ["WeightRange"] = "Weight Range",
        ["Rounds"] = "Rounds",
        ["Break"] = "Break",
        ["WeightClasses"] = "Weight Classes",
        ["Day"] = "Day",
        ["Judges"] = "Judges",
        ["AutoMatchMaker"] = "Auto Match Maker",
        ["Score"] = "Score",
        ["Bout"] = "Bout",
        ["Red"] = "Red",
        ["Blue"] = "Blue",
        ["Winner"] = "Winner",
        ["Method"] = "Method",
        ["Round"] = "Round",
        ["SearchWinner"] = "Search Winner",
        ["Scoreboard"] = "Scoreboard",
        ["BoutNo"] = "Bout No.",
        ["JudgesCount"] = "Judges Count",
        ["Judge"] = "Judge",
        ["RefereeName"] = "Referee Name",
        ["RedTotal"] = "Red Total",
        ["BlueTotal"] = "Blue Total",
        ["RedPointsWarnings"] = "Red points / warnings",
        ["BluePointsWarnings"] = "Blue points / warnings",
        ["RedPoints"] = "Red Points",
        ["BluePoints"] = "Blue Points",
        ["Total"] = "Total",
        ["Warning"] = "Warning",
        ["BetterStyle"] = "Better style",
        ["BetterDefense"] = "Better defense",
        ["Other"] = "Other",
        ["ResultMethod"] = "Result Method",
        ["ResultRound"] = "Result Round",
        ["SaveScore"] = "Save Score",
        ["NextFight"] = "Next Fight",
        ["ShowWinner"] = "Show Winner",
        ["ReportsTitle"] = "Reports",
        ["TournamentTitle"] = "Tournament Title",
        ["ReportType"] = "Report Type",
        ["Refresh"] = "Refresh",
        ["ExportCsv"] = "Export CSV",
        ["ExportPdf"] = "Export PDF",
        ["Print"] = "Print",
        ["Gold"] = "Gold",
        ["Silver"] = "Silver",
        ["Bronze"] = "Bronze",
        ["Medal"] = "Medal",
        ["Fighter"] = "Fighter"
    };

    private static readonly Dictionary<string, string> Polish = new()
    {
        ["Language"] = "Jezyk",
        ["English"] = "Angielski",
        ["Polish"] = "Polski",
        ["MainTitle"] = "MuaythaiApp",
        ["Fighters"] = "Zawodnicy",
        ["Clubs"] = "Kluby",
        ["Categories"] = "Kategorie",
        ["Matches"] = "Walki",
        ["FightResults"] = "Wyniki Walk",
        ["MedalTable"] = "Tabela Medali",
        ["Reports"] = "Raporty",
        ["ChangePasswords"] = "Zmien Hasla",
        ["DatabaseSync"] = "Synchronizacja Bazy",
        ["CurrentDatabase"] = "Aktualna baza",
        ["SharedDatabasePath"] = "Sciezka wspolnej bazy",
        ["DatabaseSyncHint"] = "Uzyj tej samej sciezki do wspolnego pliku bazy sieciowej na obu komputerach, aby widziec te same dane turnieju.",
        ["DatabaseSyncInfo"] = "Jesli docelowy plik bazy jeszcze nie istnieje, aplikacja automatycznie skopiuje do niego biezace dane.",
        ["DatabaseSyncSaved"] = "Ustawienia synchronizacji bazy zapisane.",
        ["DatabaseSyncSaveFailed"] = "Nie udalo sie zapisac ustawien synchronizacji bazy",
        ["SharedDatabasePathRequired"] = "Wpisz sciezke wspolnej bazy.",
        ["DatabasePathMustEndWithDb"] = "Sciezka bazy musi konczyc sie na .db",
        ["InvalidDatabasePath"] = "Sciezka bazy jest nieprawidlowa.",
        ["UsingLocalDatabase"] = "Aplikacja uzywa teraz lokalnej bazy tego komputera.",
        ["UsingLocalDatabaseLabel"] = "Uzywana lokalna baza",
        ["UsingSharedDatabaseLabel"] = "Uzywana wspolna baza",
        ["UseLocalDatabase"] = "Uzyj Lokalnej Bazy",
        ["Save"] = "Zapisz",
        ["Cancel"] = "Anuluj",
        ["Logout"] = "Wyloguj",
        ["LoggedInAsAdministrator"] = "Zalogowano jako administrator",
        ["LoggedInAsUser"] = "Zalogowano jako uzytkownik",
        ["FullAccessEnabled"] = "Pelny dostep wlaczony. Administrator moze edytowac zawodnikow, kluby, walki i hasla.",
        ["LimitedAccessEnabled"] = "Ograniczony dostep wlaczony. To konto moze tylko przegladac kategorie, wyniki walk, tabele medali i raporty.",
        ["FighterRegistration"] = "Rejestracja Zawodnikow",
        ["FirstName"] = "Imie",
        ["LastName"] = "Nazwisko",
        ["Club"] = "Klub",
        ["BirthYear"] = "Rok Urodzenia",
        ["Age"] = "Wiek",
        ["Weight"] = "Waga",
        ["Gender"] = "Plec",
        ["Category"] = "Kategoria",
        ["WeightClass"] = "Kategoria Wagowa",
        ["AddFighter"] = "Dodaj Zawodnika",
        ["UpdateFighter"] = "Aktualizuj Zawodnika",
        ["DeleteFighter"] = "Usun Zawodnika",
        ["ClearForm"] = "Wyczysc Formularz",
        ["SearchFighter"] = "Szukaj Zawodnika",
        ["SortBy"] = "Sortuj Wedlug",
        ["Name"] = "Imie",
        ["Surname"] = "Nazwisko",
        ["ClubsTitle"] = "Kluby",
        ["ClubName"] = "Nazwa Klubu",
        ["Coach"] = "Trener",
        ["City"] = "Miasto",
        ["Country"] = "Kraj",
        ["AddClub"] = "Dodaj Klub",
        ["UpdateClub"] = "Aktualizuj Klub",
        ["DeleteClub"] = "Usun Klub",
        ["Clear"] = "Wyczysc",
        ["Search"] = "Szukaj",
        ["ExistingClubs"] = "Istniejace Kluby",
        ["CategoryManagement"] = "Zarzadzanie Kategoriami",
        ["Division"] = "Dywizja",
        ["Info"] = "Informacja",
        ["All"] = "Wszystko",
        ["WeightRange"] = "Zakres Wagi",
        ["Rounds"] = "Rundy",
        ["Break"] = "Przerwa",
        ["WeightClasses"] = "Klasy Wagowe",
        ["Day"] = "Dzien",
        ["Judges"] = "Sedziowie",
        ["AutoMatchMaker"] = "Automatyczne Losowanie",
        ["Score"] = "Punktacja",
        ["Bout"] = "Pojedynek",
        ["Red"] = "Czerwony",
        ["Blue"] = "Niebieski",
        ["Winner"] = "Zwyciezca",
        ["Method"] = "Metoda",
        ["Round"] = "Runda",
        ["SearchWinner"] = "Szukaj Zwyciezcy",
        ["Scoreboard"] = "Tablica Wynikow",
        ["BoutNo"] = "Nr Walki",
        ["JudgesCount"] = "Liczba Sedziow",
        ["Judge"] = "Sedzia",
        ["RefereeName"] = "Sedzia Glowny",
        ["RedTotal"] = "Suma Czerwony",
        ["BlueTotal"] = "Suma Niebieski",
        ["RedPointsWarnings"] = "Punkty / ostrzezenia czerwony",
        ["BluePointsWarnings"] = "Punkty / ostrzezenia niebieski",
        ["RedPoints"] = "Punkty Czerwony",
        ["BluePoints"] = "Punkty Niebieski",
        ["Total"] = "Suma",
        ["Warning"] = "Ostrzezenie",
        ["BetterStyle"] = "Lepszy styl",
        ["BetterDefense"] = "Lepsza obrona",
        ["Other"] = "Inne",
        ["ResultMethod"] = "Metoda Wyniku",
        ["ResultRound"] = "Runda Wyniku",
        ["SaveScore"] = "Zapisz Punkty",
        ["NextFight"] = "Nastepna Walka",
        ["ShowWinner"] = "Pokaz Zwyciezce",
        ["ReportsTitle"] = "Raporty",
        ["TournamentTitle"] = "Nazwa Turnieju",
        ["ReportType"] = "Typ Raportu",
        ["Refresh"] = "Odswiez",
        ["ExportCsv"] = "Eksport CSV",
        ["ExportPdf"] = "Eksport PDF",
        ["Print"] = "Drukuj",
        ["Gold"] = "Zloto",
        ["Silver"] = "Srebro",
        ["Bronze"] = "Braz",
        ["Medal"] = "Medal",
        ["Fighter"] = "Zawodnik"
    };

    public static event Action? LanguageChanged;

    public static AppLanguage CurrentLanguage { get; private set; } = AppLanguage.English;

    public static void SetLanguage(AppLanguage language)
    {
        if (CurrentLanguage == language)
            return;

        CurrentLanguage = language;
        LanguageChanged?.Invoke();
    }

    public static string T(string key)
    {
        var source = CurrentLanguage == AppLanguage.Polish ? Polish : English;
        return source.TryGetValue(key, out var value) ? value : key;
    }
}
